eclipse-simrel/simrel.build

- mat.aggrcon
> Update to MAT 1.15.0 for 2023-12 M1

- mylyn.aggrcon
Contribute Mylyn 4.1.0 M1 to SimRel
https://download.eclipse.org/mylyn/updates/milestone/S202310031800
> Contribute Mylyn 4.1.0 M1 to SimRel

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.27 M1-20231004-1453
- RAP Tools 3.27 M1-20231004-1453
> Publish RAP 3.27 M1 for 2023-12 M1

- passage.aggrcon
Dear @merks , 
can I ask you to review this Passage  2.10.0 M2 contribution for Eclipse 2023-12 M2, as Passage Team leader @ruspl-afed is in hospital right now and completely unavailable.
> Contribute Passsage 2.10.0 M2 for 2023-12 M2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202311141700
> Contribute Mylyn 4.1.0 M3 to SimRel

- mat.aggrcon
MAT Contribution to SimRel - passes tests.
May need @krumts to do the merge as I'm a committer on MAT but not a committer on simrel.build.
> Eclipse Memory Analyzer contribution to SimRel 2023-12 M3

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.27 M3-20231115-1312
- RAP Tools 3.27 M3-20231115-1312
> Publish RAP 3.27 M3 for 2023-12 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.10.0-M3/ldc/
> Contribute Eclipse Passage 2.10.0 M3 to SimRel

- epp-mpc.aggrcon
Fix issue with duplicate version of httpclient.
> [MPC] MPC 1.10.2 contribution for 2023-12 RC1

- windowbuilder.aggrcon
- xwt.aggrcon
The WindowBuilder feature that relies on it also needs to be disabled.
> Disable XWT from the aggregation

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.27 RC1-20231122-0036
- RAP Tools 3.27 RC1-20231122-0037
> Publish RAP 3.27 RC1 for 2023-12 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.10.0-M3/ldc/
> Contribute Passage 2.10.0 RC1 for 2023-12 RC1

- gmp-gmf-runtime.aggrcon
No content change, just promoted RC1 as the actual release.
> GMF Runtime 1.16.2 final

- simrel.aggr
- simrel.aggran
> Remove simrel-extras from the aggregation

- emf-parsley.aggrcon
I discovered a small bug that I fixed.
> Contribute (patched) EMF Parsley 1.15.0

- m2e.aggrcon
Contribute M2E 2.5.0 release: https://github.com/eclipse-m2e/m2e-core/pull/1614
> Contribute M2E 2.5.0

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.10.0-RC2/ldc/
> Contribute Passage 2.10.0 RC2 for 2023-12 RC2

- passage.aggrcon
https://download.eclipse.org/passage/updates/release/2.10.0/ldc/
> Contribute Passage 2.10.0 for 2023-12 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.1.0
> Contribute Mylyn 4.1.0 Release for 2023-12 RC2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.27 RC2-20231129-0035
- RAP Tools 3.27 RC2-20231129-0036
> Publish RAP 3.27 RC2 for 2023-12 RC2

- ep.aggrcon
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1615
> Simrel updates for Eclipse and Equinox RC2a for 2023-12 RC2a

- ecf.aggrcon
- emf-emf.aggrcon
> Contribute EMF 2.37 M1 for 2024-03 M1

- mylyn-docs.aggrcon
Base contribution for SimRel 2024-03 M1
> Contribute a version Mylyn Docs compatible with Guava 33

- ep.aggrcon
> Simrel updates for Eclipse and Equinox for 2024-03 M1

- mylyn-docs.aggrcon
The contribution points at a nightly build and hence the underlying versions can change arbitrarily at any time.
> Fix mylyn-docs

- simrel.aggr
https://github.com/eclipse-simrel/simrel.build/pull/168
> Remove references to deleted Window Builder feature.

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.28 M1-20240110-1627
- RAP Tools 3.28 M1-20240110-1627
>  Publish RAP 3.28 M1 for 2024-03 M1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.11.0-M1/ldc/
> Eclipse Passage 2.11.0 M1 for 2024-03 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202401051748
> Eclipse Mylyn 4.2.0 M1 for 2024-03 M1

- ecf.aggrcon
ECF in simrel is at 3.14.40.  We released 3.14.41 and want to contribute to simrel
> Update ECF contribution to simrel to ECF v3.14.41

- tm.aggrcon
Change-Id: I80c2bd30c64c495ac6230ae3ed70977d14edda0e
> Contribute TM 4.5.600

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.11.0-M2/ldc/
> Eclipse Passage 2.11.0 M2 for 2024-03 M2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202401311712
> Eclipse Mylyn 4.2.0 M2 for 2024-03 M2

- tracecompass.aggrcon
Change-Id: I997d860d5d702ee9872a6f940592d2e5302510df
> Trace Compass contribution for 2024-03 M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.28 20240201-0741
> Publish RAP 3.28 M2 for 2024-03 M2

- simrel.aggr
- simrel.aggran
- tm4e.aggrcon
see https://github.com/eclipse/tm4e/releases/tag/0.10.0
> Update TM4E to 0.10.0

- SimRel.setup
https://github.com/eclipse-simrel/simrel.build/issues/206
> Don't create resources during bootstrap but rather after the cloning

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.28 M3-20240220-1342
- RAP Tools 3.28 M3-20240220-1342
> Publish RAP 3.28 M3 for 2024-03 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.11.0-M3/ldc/
> Eclipse Passage 2.11.0 M3 for 2024-03 M3

- m2e.aggrcon
Part of https://github.com/eclipse-m2e/m2e-core/pull/1697
> Contribute M2E 2.6.0

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202402211916
> Eclipse Mylyn 4.2.0 M3 for 2024-03 M3

- mdt-bpmn2.aggrcon
- simrel.aggran
- soa-bpmn2-modeler.aggrcon
Also update the simrel.aggran with reconciled projects that reflect the latest release records, include ranking information, as well as the filters used for reconciling the Git repositories.
> Disable BPMN contributions

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.11.0-RC1/ldc/
> Eclipse Passage 2.11.0 RC1 for 2024-03 RC1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.28 RC1-20240228-1122
- RAP Tools 3.28 RC1-20240228-1121
> Publish RAP 3.28 RC1 for 2024-03 RC1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202402281814
> Eclipse Mylyn 4.2.0 RC1 for 2024-03 RC1

- cdt.aggrcon
(Sorry for the last minute contribution)
> CDT 11.5.0 RC1 for 2024-03 RC1

- lsp4e.aggrcon
Fixes https://github.com/eclipse/lsp4e/issues/936
> Contribute LSP4E 0.24.8

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/2.11.0-RC2/ldc/
> Eclipse Passage 2.11.0 RC2 for 2024-03 RC2

- tracecompass.aggrcon
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
> Trace Compass contribution for 2024-03 RC2

- dtp.aggrcon
- simrel.aggran
> Contribute datatools 1.16.1 for 2024-03 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202403051857
> Eclipse Mylyn 4.2.0 RC2 for 2024-03 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.2.0
> Eclipse Mylyn 4.2.0 for 2024-03

- ep.aggrcon
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1967
> Simrel updates for Eclipse and Equinox for 2024-06 M1a

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.29 M1-20240410-1511
- RAP Tools 3.29 M1-20240410-1511
> Publish RAP 3.29 M1 for 2024-06 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202404101612
> Eclipse Mylyn 4.3.0 M1 for 2024-06 M1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.0.0-M1/
> Eclipse Passage 3.0.0 M1 for 2024-06 M1

- cdt.aggrcon
- simrel.aggr
This is unlikely to be the final version.
> Add CDT's cdt-lsp component to SimRel for 2024-06

- ep.aggrcon
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2000
> Simrel updates for Eclipse and Equinox for 2024-06 M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.29 M2-20240430-1618
- RAP Tools 3.29 M2-20240430-1618
> Publish RAP 3.29 M2 for 2024-06 M2

- oomph.aggrcon
- simrel.aggran
Also update simrel.aggran layout and reconcile project links.
> Contribute Oomph 1.33 M2 for 2024-06 M2

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.0.0-M2/
> Eclipse Passage 3.0.0 M2 for 2024-06 M2

- mdt-papyrus.aggrcon
- xwt.aggrcon
Enable and update XWT to release 1.9.100 for M2
Supersedes https://github.com/eclipse-simrel/simrel.build/pull/326
> Contribute Papyrus 6.7 M2 for 2024-06 M2

- lsp4j.aggrcon
xref https://github.com/eclipse-lsp4j/lsp4j/issues/807
> LSP4J 0.23.0 for 2024-06

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202405221352
> Eclipse Mylyn 4.3.0 M3 for 2024-06 M3

- mdt-papyrus.aggrcon
Change-Id: Ib16b7675bc599df214ba571310f9cd93cccbf1d3
> Eclipse Papyrus 6.7.0 M3 for 2024-06 M34

- cdt.aggrcon
> CDT 11.6.0 M3a and CDT-LSP 2.0.0 M3a for 2024-06 M3a (signing fix)

- emf-emf-rap.aggrcon
- emf-emf.aggrcon
- pom.xml
Also go back to Tycho 4.0.7 so that we can track invalidly signed contents contributions.
> Contribute EMF 2.38.0 release for 2024-06 RC1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202405261725
> Eclipse Mylyn 4.3.0 RC1 for 2024-06 RC1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.29 RC1-20240529-1507
- RAP Tools 3.29 RC1-20240529-1507
> Publish RAP 3.29 RC1 for 2024-06 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.0.0-RC1/
> Eclipse Passage 3.0.0 RC1 for 2024-06 RC1

- mdt-papyrus.aggrcon
Change-Id: I117935d8d39a59d1f0dc0660d50420bcb1819ec3
> Eclipse Papyrus 6.7.0 RC1 for 2024-06 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.0.0-RC2/
> Eclipse Passage 3.0.0 RC2 for 2024-06 RC2

- m2e.aggrcon
Part of https://github.com/eclipse-m2e/m2e-core/pull/1775
> Contribute M2E 2.6.1

- emft-ecoretools.aggrcon
> Ecore Tools 3.5.1 (final location)

- passage.aggrcon
https://download.eclipse.org/passage/updates/release/3.0.0/ldc/
> Eclipse Passage 3.0.0 for 2024-06

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.3.0
> Eclipse Mylyn 4.3.0 for 2024-06

- xwt.aggrcon
Change-Id: I353eb4141ec5e82b750d896ba02a3bcfed204431
> [XWT] Update contribution for 2024-06RC2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 3.29 RC2-20240605-1615
- RAP Tools 3.29 RC2-20240605-1615
> Publish RAP 3.29 RC2 for 2024-06 RC2

- mdt-papyrus.aggrcon
Change-Id: I080a48811deff491aa1f68c10b609ad13cfa19b2
> Eclipse Papyrus 6.7.0 RC2 for 2024-06 RC2

- sirius.aggrcon
> Sirius Desktop 7.4.1

- sirius.aggrcon
See https://projects.eclipse.org/projects/modeling.sirius/releases/sirius-desktop-7.4.2
> Sirius Desktop 7.4.2

- mylyn.aggrcon
https://github.com/eclipse-simrel/simrel.build/issues/438
> Disable Mylyn's gerrit features

- mylyn.aggrcon
https://github.com/eclipse-simrel/simrel.build/issues/438
> Exclude org.apache.httpcomponents.httpcore 4.4.16.v20221207-1049

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.1.0-M1/ldc/
> Eclipse Passage 3.1.0 M1 for 2024-09 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202407100318
> Eclipse Mylyn 4.4.0 M1 for 2024-09 M1

- rap-tools.aggrcon
- rap.aggrcon
- simrel.aggran
- RAP Runtime 4.0 M1-20240710-1534
- RAP Tools 4.0 M1-20240710-1541
- Adjust simrel.aggran with RAP release details
> Publish RAP 4.0 M1 for 2024-09

- mylyn.aggrcon
https://github.com/eclipse-simrel/simrel.build/pull/458
> Contribute to mylyn m1a to accommodate egit 7.x

- egit.aggrcon
https://github.com/eclipse-simrel/simrel.build/pull/458
> Contribute EGit m1 with missing jetty 12 dependency

- tm.aggrcon
https://download.eclipse.org/tm/updates/4.5.700-SNAPSHOT/repository/
> Contribute TM 4.700 for M2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202407311626
> Eclipse Mylyn 4.4.0 M2 for 2024-09 M2

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.1.0-M2/ldc/
> Eclipse Passage 3.1.0 M2 for 2024-09 M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.0 M2-20240731-2002
- RAP Tools 4.0 M2-20240731-2002
> Publish RAP 4.0 M2 for 2024-09 M2

- oomph.aggrcon
https://github.com/eclipse-orbit/orbit-simrel/issues/40
> Explicitly exclude org.apache.commons.logging 1.2.0.v20180409-1502

- emf-services.aggrcon
- simrel.aggr
> EMF Services 1.14.0rc1 for SimRel 2024-09

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202408201930
> Eclipse Mylyn 4.4.0 M3 for 2024-09 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/3.1.0-M3/
> Eclipse Passage 3.1.0 M3 for 2024-09 M3

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.0 M3-20240821-1916
- RAP Tools 4.0 M3-20240821-1916
> Publish RAP 4.0 M3 for 2024-09 M3

- sirius.aggrcon
> Sirius Desktop 7.4.3rc1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202408280745
> Eclipse Mylyn 4.4.0 RC1 for 2024-09 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202408280821
> Eclipse Passage 3.1.0 RC1 for 2024-09 RC1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.0 RC1-20240828-1126
- RAP Tools 4.0 RC1-20240828-1126
> Publish RAP 4.0 RC1 for 2024-09 RC1

- linuxtools.aggrcon
> Refresh Linux Tools again for 2024-09 RC1

- xwt.aggrcon
Change-Id: Iaff81d70c375db1ba5a0aab7542053aa44cc9d9d
> [XWT] Disable XWT for 2024-09 RC1

- sirius.aggrcon
> Sirius Desktop 7.4.3 (final location)

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202409011834
> Eclipse Passage 3.1.0 RC2 for 2024-09 RC2

- passage.aggrcon
https://download.eclipse.org/passage/updates/release/3.1.0
> Eclipse Passage 3.1.0 for 2024-09

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202409011831
> Eclipse Mylyn 4.4.0 RC2 for 2024-09 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.4.0
> Eclipse Mylyn 4.4.0 for 2024-09

- ep.aggrcon
@MohananRahul 
I created this so it can be be tested now and merged when confirmed/verified by the Platform team.
> Simrel updates (RC2a) for Eclipse and Equinox for 2024-09 RC2

- m2e.aggrcon
Part of https://github.com/eclipse-m2e/m2e-core/pull/1822
> Contribute M2E 2.6.2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.0 RC2-20240904-0717
- RAP Tools 4.0 RC2-20240904-0717
> Publish RAP 4.0 RC2 for 2024-09 RC2

- emf-services.aggrcon
> EMF Transaction 1.14.1 M1

- emf-emf-rap.aggrcon
- emf-emf.aggrcon
- simrel.aggran
- Update simrel.aggran to show org.eclipse.orbit bundles as 3rd party.
> Update EMF 2.40 M1 for 2024-12 M1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202410021614
> Eclipse Passage 4.0.0 M1 for 2024-12 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202410021731
> Eclipse Mylyn 4.5.0 M1 for SimRel 2024-12 M1

- emft-ecoretools.aggrcon
> Ecore Tools 3.5.2rc1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202410221753
> Eclipse Mylyn 4.5.0 M2 for SimRel 2024-12 M2

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202410221826
> Eclipse Passage 4.0.0 M2 for 2024-12 M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 M2-20241023-1329
- RAP Tools 4.1 M2-20241023-1329
> Publish RAP 4.1 M2 for 2024-12 M2

- gmp-gmf-runtime.aggrcon
> GMF Runtime 1.16.5rc1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 M3-20241113-1015
- RAP Tools 4.1 M3-20241113-1015
> Publish RAP 4.1 M3 for 2024-12 M3

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202411121852
> Eclipse Mylyn 4.5.0 M3 for SimRel 2024-12 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202411132000
> Eclipse Passage 4.0.0 M3 for 2024-12 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202411191616
> Eclipse Passage 4.0.0 RC1 for 2024-12 RC1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202411191610
> Eclipse Mylyn 4.5.0 RC1 for SimRel 2024-12 RC1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 RC1-20241120-1106
- RAP Tools 4.1 RC1-20241120-1105
> Publish RAP 4.1 RC1 for 2024-12 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202411240850
> Eclipse Passage 4.0.0 RC2 for 2024-12 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202411241624
> Eclipse Mylyn 4.5.0 RC2 for SimRel 2024-12 RC2

- passage.aggrcon
https://download.eclipse.org/passage/updates/release/4.0.0
> Eclipse Passage 4.0.0 for 2024-12

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.5.0
> Eclipse Mylyn 4.5.0 for 2024-12

- tracecompass.aggrcon
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
> Trace Compass contribution for 2024-12 RC2

- m2e.aggrcon
Part of https://github.com/eclipse-m2e/m2e-core/pull/1899
> Contribute M2E 2.7.0

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 RC2-20241127-1523
- RAP Tools 4.1 RC2-20241127-1523
> Publish RAP 4.1 RC2 for 2024-12 RC2

- tracecompass.aggrcon
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
> Switch Trace Compass URL to 10.2.0 release

- emft-ecoretools.aggrcon
- sirius.aggrcon
See-also: https://projects.eclipse.org/projects/modeling.sirius/releases/sirius-desktop-7.4.5
> Sirius Desktop 7.4.5

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202412081517
> Eclipse Mylyn 4.6.0 M0 for SimRel 2025-03 M0

- dtp.aggrcon
- ep.aggrcon
- The datatools site includes lucene 10.
> Contribute platform and datatools with relaxed lucene requirements

- sirius.aggrcon
> Sirius Desktop 7.4.6

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202501081420
> Eclipse Passage 4.1.0 M1 for 2025-03 M1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 M1-20250108-1548
- RAP Tools 4.1 M1-20250108-1547
> Publish RAP 4.2 M1 for 2025-04 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202501081607
> Eclipse Mylyn 4.6.0 M1 for SimRel 2025-03 M1

- ecf.aggrcon
https://github.com/eclipse-simrel/simrel.build/issues/699
> Disable the features contributed by ECF

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202501281341
> Eclipse Passage 4.1.0 M2 for 2025-03 M2

- gmp-gmf-runtime.aggrcon
> GMF Runtime 1.16.6rc1

- sirius.aggrcon
> Sirius Desktop 7.4.7M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.1 M2-20250130-0759
- RAP Tools 4.1 M2-20250130-0759
> Publish RAP 4.2 M2 for 2025-04 M2

- modisco.aggrcon
org.apache.commons.commons-beanutils dependency
> [modisco] 1.5.6M3 for 2025-03 avoiding

- ep.aggrcon
- Update the org.eclipse.equinox.slf4j with yesterday's changes.
> Simrel updates for Eclipse and Equinox for 2025-03 pre-M3

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.2 M3-20250214-0926
- RAP Tools 4.2 M3-20250214-0926
> Publish RAP 4.2 M3 for 2025-04 M3

- modisco.aggrcon
> [modisco] 1.5.6M3 for 2025-03 avoiding org.apache.commons.jxpath etc

- gmp-graphiti.aggrcon
- This is to accommodate the removal of deprecated APIs from GEF.
> Update to a graphiti 1.19.3 milestone

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202502191853/
> Eclipse Mylyn 4.6.0 M3 for SimRel 2025-03 M3

- gmp-gmf-runtime.aggrcon
> GMF Runtime 1.16.6: final URL

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202502251512
> Eclipse Mylyn 4.6.0 RC1 for SimRel 2025-03 RC1

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202502251648
> Eclipse Passage 4.1.0 RC1 for 2025-03 RC1

- sirius.aggrcon
> Sirius Desktop 7.4.7

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.2 RC1-20250226-0730
- RAP Tools 4.2 RC1-20250226-0730
> Publish RAP 4.2 RC1 for 2025-04 RC1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.2 RC2-20250303-0902
- RAP Tools 4.2 RC2-20250303-0901
> Publish RAP 4.2 RC2 for 2025-03 RC2

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202503031858
> Eclipse Passage 4.1.0 RC2 for 2025-03 RC2

- m2e.aggrcon
Part of https://github.com/eclipse-m2e/m2e-core/pull/1955.
> Contribute M2E 2.8.0

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202503040505
> Eclipse Mylyn 4.6.0 RC2 for SimRel 2025-03

- passage.aggrcon
https://download.eclipse.org/passage/updates/release/4.1.0/
> Eclipse Passage 4.1.0 for 2025-03

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.6.0/
> Eclipse Mylyn 4.6.0 for SimRel 2025-03

- oomph.aggrcon
- simrel.aggran
- Update simrel.aggran as well.
> Contribute Oomph 1.36.0 release for 2025-03 RC2

- cdt.aggrcon
This is the same content as previously there, but now at their final URLs.
> CDT 12.0.0 and CDT LSP 3.0.0 for 2025-03

- Jenkinsfile
- Jenkinsfile-reporeports
- pom.xml
- simrel.aggr
- simrel.aggran
> Begin staging for 2025-06

- emft-ecoretools.aggrcon
- simrel.aggr
> Add Ecore Tools feature into the Modeling category

- sirius.aggrcon
> Sirius Desktop 7.4.8

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202504090913
> Eclipse Passage 4.2.0 M1 for 2025-06 M1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.3 M1-20250409-0726
- RAP Tools 4.3 M1-20250409-0726
> Publish RAP 4.3 M1 for 2025-06 M1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202504091233
> Eclipse Mylyn 4.7.0 M1 for 2025-06 M1

- cdt.aggrcon
Part of https://github.com/eclipse-cdt/cdt-lsp/issues/480
> CDT LSP 3.1.0 for 2025-06 M1

- SimRel.setup
- ep.aggrcon
- Update setup to configure branches for rebasing.
> Contribute an early version of the Platform M2 for early testing

- webtools.aggrcon
The latest I-build, until JIPP is restored.
> Contribute WTP 3.38 build for 2025-06

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202505071621
> Eclipse Passage 4.2.0 M2 for 2025-06 M2

- sirius.aggrcon
> Sirius Desktop 7.4.9 for 2025-06 M3

- emft-eef.aggrcon
> EEF 2.1.7 for 2025-06

- sirius.aggrcon
> Sirius Desktop 7.4.10rc1 for 2025-06 M3

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.3 M3-20250518-2338
- RAP Tools 4.3 M3-20250518-2338
> Publish RAP 4.3 M3 for 2025-06 M3

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202505210844
> Eclipse Passage 4.2.0 M3 for 2025-06 M3

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202505220303
> Eclipse Mylyn 4.7.0 M3 for 2025-06 M3

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.3 RC1-20250526-2335
- RAP Tools 4.3 RC1-20250526-2335
> Publish RAP 4.3 RC1 for 2025-06 RC1

- sirius.aggrcon
> Sirius Desktop 7.4.10 (final URL)

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202505310947
> Eclipse Passage 4.2.0 RC2 for 2025-06 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202506040726
> Eclipse Mylyn 4.7.0 RC2 for 2025-06 RC2

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/release/4.7.0
> Eclipse Mylyn 4.7.0 for 2025-06

- m2e.aggrcon
Part of
- https://github.com/eclipse-m2e/m2e-core/pull/2001
> Contribute M2E 2.9.0

- ep.aggrcon
https://github.com/eclipse-simrel/simrel.build/pull/932
> Simrel updates for Eclipse and Equinox for 2025-09 M1

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.4 M1-20250709-1612
- RAP Tools 4.4 M1-20250709-1612
> Publish RAP 4.4 M1 for 2025-09 M1

- mdt-papyrus.aggrcon
- xwt.aggrcon
Change-Id: Iea1c53eb120c9acb38ef968704290a7dd7dd1c73
> [Papyrus] [XWT] will not contribute to the 2025-09 release train

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202507300531
> Eclipse Passage 4.3.0 M2 for 2025-09 M2

- rap-tools.aggrcon
- rap.aggrcon
- RAP Runtime 4.4 M2-20250730-1549
- RAP Tools 4.4 M2-20250730-1549
> Publish RAP 4.4 M2 for 2025-09 M2

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202508271408
> Eclipse Passage 4.3.0 RC1 for 2025-09 RC1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202508271408
> Eclipse Mylyn 4.8.0 RC1 for 2025-09 RC1

- gmp-gmf-runtime.aggrcon
> GMF Runtime 1.16.7 (final location)

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202509020726
> Eclipse Passage 4.3.0 RC2 for 2025-09 RC2

- m2e.aggrcon
Part of
- https://github.com/eclipse-m2e/m2e-core/pull/2032
> Contribute M2E 2.9.1

- mylyn.aggrcon
https://download.eclipse.org/mylyn/updates/milestone/S202509031222
> Eclipse Mylyn 4.8.0 RC2 for 2025-09 RC2

- ep.aggrcon
- Update to 20250919-1800.
Fixes https://github.com/eclipse-simrel/simrel.build/issues/1040
> Add org.eclipse.pde.osgitest.dependencies.feature.feature.group

- sirius.aggrcon
> Sirius Desktop 7.4.12

- passage.aggrcon
https://download.eclipse.org/passage/updates/milestone/S202510081636
> Eclipse Passage 4.4.0 M1 for 2025-12 M1
