ep.aggrcon

Follow-up of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1235

Remove unused products removed from Eclipse-Platform

---

simrel.aggr
simrel.aggran

These dependencies were coming from the Platform repository but are collectively replaced by org.eclipse.orbit.xml-apis-ext bundle now.

Provide repo with org.w3c dependencies of batik

---

ep.aggrcon

Those bundles are mentioned in the N&N entry in https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/85 and are in general the more recent original versions from Maven-Central and are not the `javax.*` once originating from old Orbit.
Therefore they should be available in the SimRel repository.
The Orbit based bundles are pulled in because they are required/included by some bundles:
I'll check if they are already there and if not yet done will provide PRs to replace them by Import-Package imports.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056

Add javax annotations providing jakarta bundles

---

ecf.aggrcon
simrel.aggr

This is to workaround:
- https://github.com/eclipse-equinox/p2/issues/381
And to enable:
- https://github.com/eclipse-packaging/packages/issues/81
in 2023-12 M3.
The Eclipse Platform is expected to contribute this for RC1 but including this from ECF allows us to start testing this in 2023-12 M3

Include ecf.filetransfer.httpclient5 in SimRel

---

ecf.aggrcon
simrel.aggr

Remove source features because the aggregator automatically includes corresponding source bundles and features for any otherwise included bundle or feature.

Update ECF to latest 3.14.40 snapshot

---

tracecompass.aggrcon

Change-Id: Ica89157aa113dd063883a5777600c06a1b8eaf5d

Trace Compass contribution for 2023-12 M3

---

pom.xml

It's not needed and this build should practically never have the need to use Tycho snapshots.
Removing this fixes dependabot as without it it properly updated Tycho version (https://github.com/akurtakov/simrel.build/pull/1 )

Remove tycho-snapshots repo

---

ecf.aggrcon
simrel.aggr

This was added as a workaround and keeping it would make it more difficult to align the version required by the platform and that provided by ECF.

Remove ECF's httpclient5 explicit feature include

---

windowbuilder.aggrcon

The milestone URL will become invalid, once the upcoming M1 is built.

Use release instead of milestone URL for WindowBuilder 1.14.0

---

m2t-acceleo.aggrcon

The previous version only partially updated the Guava ranges.
See https://github.com/eclipse-acceleo/acceleo/pull/137 for the additional changes in this respin.

Contribute a version of Acceleo 3.7 compatible with Guava 33 (respin)

---

simrel.aggr
sirius.aggrcon

This version includes https://github.com/eclipse-sirius/sirius-desktop/pull/223 which brings compatibbility with Guava 33.

Sirius Desktop 7.4.0M1

---

lsp4j.aggrcon

This is a dependency update to widen Guava and include newer websocket dependency in p2 repo

LSP4J 0.21.2 for 2024-03 M1

---

buildship.aggrcon

This uses a snapshop repo which is not a good thing, but since there is nothing downstream from buildship in terms of dependencies, this should not cause any problems. I really want to eliminate the older guava version from M1 and this is the only way.
https://github.com/eclipse/buildship/pull/1292

Update buildship to 3.1.9

---

passage.aggrcon

https://download.eclipse.org/passage/updates/release/2.11.0/ldc/

Eclipse Passage 2.11.0 for 2024-03

---

gef.aggrcon

The milestone repository will be deleted with the upcoming release. Both repositories are identical, so this change merely avoids potential build errors during the 2024-06 release cycle

Use release repository url for GEF Classic 3.19

---

emf-services.aggrcon

With https://github.com/eclipse-emf-parsley/emf-parsley/issues/93 the last dependency on EMF Query in the SimRel is gone.

EMF Services: disable EMF Query

---

ecp.aggrcon
simrel.aggr
simrel.aggran

(Draft) PR to see implications

Prepare ECP/EMFForms Removal

---

cdt.aggrcon

We decided to deploy some important fixes into RC1 to maximize testing time.

CDT 11.6.0 RC1 and CDT-LSP 2.0.0 RC1 for 2024-06 RC1

---

cdt.aggrcon

Applies signing fix for missing gpg signature
See https://github.com/eclipse-cdt/cdt-lsp/issues/332

CDT-LSP 2.0.0 RC1a for 2024-06 RC1

---

gef.aggrcon
pom.xml

- Specifically version 1.1.600.v20220215-0126 from https://download.eclipse.org/efxclipse/runtime-released/3.9.0/site
https://github.com/eclipse-simrel/simrel.build/issues/399 https://github.com/eclipse-packaging/packages/issues/171

Exclude org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group

---

gef.aggrcon

https://github.com/eclipse-simrel/simrel.build/issues/438

Exclude org.apache.commons.jxpath/1.3.0.v200911051830 from gef.aggrcon

---

gef.aggrcon
oomph.aggrcon

- Move org.apache.commons.logging 1.2.0.v20180409-1502 exclusion to GEF's contribution.

Contribute Oomph 1.34 M3 for 2024-09 M3

---

buildship.aggrcon

See [Buildship 3.1.10 announcement](https://discuss.gradle.org/t/buildship-3-1-10-is-now-available/49045).
@donat Could you please approve or are there reasons not to contribute Buildship 3.1.10 to the Eclipse IDE 2024-09 release?

Contribute Buildship 3.1.10

---

ep.aggrcon
simrel.aggr

- Update simrel.aggr to include a riscv64 configuration.

Contribute a pre-m2 version of the platform with riscv64 support

---

ep.aggrcon

- Also the Platform products now how touchpoints to require Java 21.

Contribute platform latest I-build with updated lucene bounds

---

cdt.aggrcon

These bundles have been manually listed for a long time (since first version of these files in 2012). However these bundles end up in the output even if not manually listed, therefore remove them being explicit.
The secondary issue with this explicit list is that there are other native bundles not listed here, so this commit also resolves this inconsistency.

Remove explicit bundles from CDT's contribution

---

cdt.aggrcon

This is a respin of CDT's M2 contribution to include the major version bump of org.eclipse.cdt.core/ui as I wanted to get the new version into SimRel ASAP to ensure everyone downstream could cope with it properly.

CDT 12.0.0 M2a for 2025-03 M2

---

ep.aggrcon
modisco.aggrcon

- Contribute a current I-build to ensure that aggregation continues to work in preparation for this weeks actual M3 contributions.
- Disable modisco to ensure that an updated modisco build with missing transitive jxpath dependencies can be tested for successful aggregation.
https://github.com/eclipse-modisco/org.eclipse.modisco/issues/1085

Simrel updates for Eclipse and Equinox for 2025-03 pre-M3

---

oomph.aggrcon
usssdk.aggrcon

- The Oomph change is temporary until there is an Oomph m2 milestone.
- The usssdk contribution will be deleted before m2.

Disable usssdk and use Oomph nightly build with no usssdk dependencies

---

egit.aggrcon
simrel.aggr

- Corresponding source bundles or features are always aggregated automatically if available in a p2 repository.

Remove explicitly dependencies on source.feature.group

---

rap-tools.aggrcon
rap.aggrcon

- RAP Runtime 4.3 M2-20250507-1338
- RAP Tools 4.3 M2-20250507-1338
This build uses Eclipse Platform 4.36 build I20250506-0940.

Publish RAP 4.3 M2 for 2025-06 M2

---

mdt-papyrus.aggrcon

Some dependencies changes have been done in "Papyrus-Desktop 7.0.0 M3". A respin could occur by tomorrow if any issues are detected during our testing.

Contribute Papyrus 7.0.0 for 2025-06 M3

---

mdt-papyrus.aggrcon

This is a respin to consider the new version of GEF that fixes a problem (#733 "Infinite loop in PaletteDrawer" [1]) also detected in Papyrus (#37 "Infinite scroll in Palette of diagrams (GMF and Sirius)" [2]).
[1] https://github.com/eclipse-gef/gef-classic/issues/733
[2] https://gitlab.eclipse.org/eclipse/papyrus/org.eclipse.papyrus-desktop/-/issues/37

Contribute Papyrus 7.0.0 for 2025-06 M3b

---

passage.aggrcon

https://download.eclipse.org/passage/updates/release/4.2.0

Eclipse Passage 4.2.0 for 2025-06

---

cdt.aggrcon

Effectively same content as what was already there, but rebuilt from the release branch.

CDT LSP 3.2.0 RC2 for 2025-06 RC2

---

ep.aggrcon
mdt-papyrus.aggrcon
simrel.aggran
webtools.aggrcon
xwt.aggrcon

- Normalize the serialization of papyrus and xwt.
- Update WTP to add temporarily the orbit milestone to provide com.sun.el.javax.el.
- Update simrel.aggran to reflect the disablment of papyrus and xwt.

Simrel updates for Eclipse and Equinox for 2025-09 M2

---

egit.aggrcon
ep.aggrcon

- Remove EGit.aggrcon's exclusion of Jetty 12.1.0.
https://github.com/eclipse-simrel/simrel.build/pull/995

Simrel updates for Eclipse and Equinox for 2025-09 RC1

---

mylyn.aggrcon

https://download.eclipse.org/mylyn/updates/release/4.8.0

Eclipse Mylyn 4.8.0 for 2025-09

---

cdt.aggrcon
pdt.aggrcon

This includes an old version of CDT to that PDT (and TCF probably) can continue to be included with the dependency on the older terminal bundles.

CDT 12.3.0 and CDT LSP 3.4.0 for 2025-12 M1
